### PR TITLE
Disable remotes

### LINKED ISSUE #35: Support disabling remotes
Flatpak allows remotes to be disabled in the system configuration without needing to remove them. This could be useful if, e.g. a user wants to install a beta app but discontinue updates for it for a short time.

### PR DESCRIPTION
**Pull request by isantop**
Allows the option to disable remotes from the Info dialog. This is useful if, for example, a user wants to temporarily stop receiving updates from a particular remote without deleting the remote (and all of the packages that have been installed from it).

Fixes #35

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — DISMISSED** [review]

**Comment by brs17** [comment]
Testing disabling flathub, once the toggle is turned off, Gnome Builder on the Pop!_Picks looses its icon. Selecting Builder, and then trying to install, fails without graphically showing an error message. On the Builder page, nothing is listed as the source from which to install but the dropdown menu shows the Ubuntu deb. 

Screenshot from 2020-04-27 13-56-54

I would expect this same behavior with other applications which default to flathub. 

If the flathub repo is disabled though, shouldn't that option not show up at all for a specific program? I notice with a program like postman which only has a flathub, the program disappears entirely (which is what I would expect).

It appears there is some logic missing dealing with hiding disabled remotes with programs that have multiple sources available.

**Review by brs17 — DISMISSED** [review]
Testing disabling flathub, once the toggle is turned off, Gnome Builder on the Pop!_Picks looses its icon. Selecting Builder, and then trying to install, fails without graphically showing an error message. On the Builder page, nothing is listed as the source from which to install but the dropdown menu shows the Ubuntu deb. 

Screenshot from 2020-04-27 13-56-54

I would expect this same behavior with other applications which default to flathub. 

If the flathub repo is disabled though, shouldn't that option not show up at all for a specific program? I notice with a program like postman which only has a flathub, the program disappears entirely (which is what I would expect).

It appears there is some logic missing dealing with hiding disabled remotes with programs that have multiple sources available.

**Comment by isantop** [comment]
@pop-os/quality-assurance I think this is ready for re-review. I think the bugs brought up in the previous QA review were bugs with Pop shop:

1) The only logic in Flatpak itself (as per the documentation) is setting the xa.disable option.
2) Repoman does not affect the logic of Pop Shop displaying things.
3) The bug only occurs until Pop Shop restarts.
4) The bug also randomly occurs in Pop Shop already without this PR.

**Comment by jacobgkau** [comment]
Disabling a remote works (sets the `xa.disable` option to `true`.) Re-enabling also works (sets the option to `false`.) 

The bug that Ben pointed out still occurs. If Flathub is disabled while the shop is open, Pop!_Picks that previously defaulted to Flathub (like Telegram and Meld) have their icons broken, and when clicking into those apps, the "Install" button doesn't work until I change the dropdown to `Ubuntu (.deb)`, if that's available for the given app. This problem goes away after closing and re-opening the shop (the icons are no longer broken, apps with .deb available default to .deb, and apps without .deb available no longer appear in the list.)

Similarly, if I search for an application (like GNOME Builder), then disable Flathub, I see the icons for any Flatpak apps in the search results disappear. If I try to click into an app that only had Flatpak available, it has an "Install" button that doesn't work. Once I modify the search (adding or removing a single character), the search results update to no longer have apps from Flathub.

These issues are bugs in the Pop!_Shop, not Repoman, and they are not regressions, since they already occur when disabling Flatpak remotes via the CLI. There is an issue open in the Pop Shop repo here: https://github.com/pop-os/shop/issues/153 With these things in mind, I think it makes sense to move forward with this and deal with the existing Pop Shop issue separately.

While regression testing, I found that the message when removing a Flatpak remote now contains a redundant sentence:

repoman-pr63-screenshot1

In dialog.py, the new sentence is on line 240, and the existing one is on line 259. One of them should probably be removed.

**Comment by isantop** [comment]
The Pop_Shop issue has also been fixed in Upstream AppCenter, and we only need to base our fork off of the latest branch there to fix it. There is a file-watcher that causes AppCenter to reload when the underlying Flatpak installation changes.

> In dialog.py, the new sentence is on line 240, and the existing one is on line 259. One of them should probably be removed.

:+1:

**Review by jacobgkau — APPROVED** [review]

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
