### PR TITLE
fix: display more error messages

### PR DESCRIPTION
**Pull request by isantop**
Taking advantage of pop-os/repolib#30, this causes repoman to display error messages if it receives an exception from repolib. The error dialog that opens contains a description of the problem and the exception text, as well as the traceback of the exception (hidden by default behind an expander so as to avoid cluttering the UI). This should greatly improve the user experience in the event of a typo in a repository or PPA.

### CODE REVIEW

**Comment by isantop** [comment]
I have found that the best way to test that this works is to attempt to add a PPA which does not exist. For example: 

`ppa:sytem76/pop`

This should display an error dialog similar to below:

image

**Comment by jacobgkau** [comment]
The cancel button is hanging out farther than the rest of the dialog box:

repoman-pr88-screenshot2

I don't see this happening in your screenshot. Also, when attempting to remove an already-added (and valid) PPA, I get an error message:

repoman-pr88-screenshot3

This is not true; the file was removed from `sources.list.d` and the PPA was removed from Repoman's list.

**Comment by isantop** [comment]
@jacobgkau I'm not seeing the issue with the cancel button, but I'll keep a close eye on it. I have updated the branch to fix the source-removal error. Can you check if that ( ab30d43 ) fixes the issues?

**Comment by jacobgkau** [comment]
`ab30d43` did fix the source-removal issue. I'm not seeing any other regressions. The cancel button is still hanging off the sides in a new user account and also on a fresh machine:

repoman-pr88-screenshot4

**Comment by isantop** [comment]
I believe the cancel button is fixed as of 24a03b8

**Review by jacobgkau — APPROVED** [review]
Looks good now.

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
