### PR TITLE
Clean up/Refactor Flatpak Code

### PR DESCRIPTION
**Pull request by isantop**
Cleans up a lot of the Flatpak code and refactors things to make the structure of the program better.

Requires #53

### CODE REVIEW

**Comment by leviport** [comment]
It looks like the dialog for adding a flatpak repo is now the same as the PPA dialog:
flatpak-dialog

Here is the PPA dialog: 
ppa-dialog

Here is what the flatpak add dialog looks like on a system without the branch:
old-flatpak-source

Removing the example on the flatpak one is probably sufficient, but a flatpak-specific example might be nice

**Review by leviport — DISMISSED** [review]
See the above issue regarding the dialog for adding flatpak repos. Other than that, this looks good!

**Comment by isantop** [comment]
They are intentionally the same. Do we think it's necessary to differentiate them? They perform the same task.

**Comment by leviport** [comment]
They perform the same task, but expect different inputs, so I believe there is value in differentiating the example inputs. Seeing an example PPA is misleading when I'm entering a .flatpakrepo, and PPA inputs fail validation when you're adding a flatpak repo.

**Review by leviport — APPROVED** [review]
looks good!

**Review by jackpot51 — APPROVED** [review]

**Comment by yangxuanx** [comment]
After the update, there was a problem


Traceback (most recent call last):
  File "/usr/bin/repoman", line 50, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 32, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .stack import Stack
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 27, in <module>
    from .list import List
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 28, in <module>
    from .dialog import AddDialog, EditDialog, ErrorDialog, DeleteDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 31, in <module>
    from . import flatpak_helper
  File "/usr/lib/python3/dist-packages/repoman/flatpak_helper.py", line 27, in <module>
    gi.require_version('Flatpak', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Flatpak not available

**Pull request merged**
