### PR TITLE
Add support for PolicyKit

### LINKED ISSUE #25: Convert Repoman to use PolicyKit instead of root.
Repoman currently runs it's GUI as root in order for things to work. This is not ideal, and instead we should use policy kit to make changes. This will allow Repoman to work on Wayland, and is required to add support for Flatpak (which requires not running as root).

### PR DESCRIPTION
**Pull request by isantop**
This PR adds support for Polkit to repoman, and changes to launching the GUI as a regular (non-root) user by default. This is required for #24

Closes #25

### CODE REVIEW

**Comment by isantop** [comment]
Reopened as Draft, since this is not ready yet.

**Comment by isantop** [comment]
@pop-os/quality-assurance This is part of what we need to get integrated into Repoman for 20.04, however, it doesn't affect the current functionality of the application and provides some nice new features for 19.10, which will improve the experience for those users. 

Thus, I think it would be good to get this into Eoan and Bionic, as well as getting us set up better for Focal.

**Comment by isantop** [comment]
For testing, please ensure that Repoman is launched and opens without asking for root access, and that it does prompt for a password once a change is made. We also need to verify that the application does not repeat the authentication request for subsequent changes (until the auth timeout).

**Comment by leviport** [comment]
I noticed a couple of things that should probably be addressed

First is that there is now an application icon for Repoman. There was not before, so I think this may be a regression
Screenshot from 2019-11-21 11-09-58

The second is that when I check/uncheck a box, a password prompt is spawned. If I enter my password, the change is made. However, if I click "cancel" on the password prompt, the change is still reflected in the UI, but it isn't actually made. If I close and reopen Repoman, that checkbox returns to the actual state.

**Comment by isantop** [comment]
@leviport I've addressed the desktop file concerns in c7877d0

The other issue is also valid, but it's proving a bit more difficult to work around.

**Comment by isantop** [comment]
@leviport Nix that, 88111bb should fix that issue too now.

**Comment by isantop** [comment]
@pop-os/quality-assurance One note for testing the desktop icon, we should ensure that it *doesn't* show up in "Show Applications" or in a search, but that it *does* show up in the dash when launched from the command line or Pop_Shop.

**Review by jackpot51 — DISMISSED** [review]

**Comment by leviport** [comment]
There seems to be a condition which makes changes in Repoman not summon the password prompt which makes the settings unchangeable. @brs17 and I both ran into it, but I've finally found a reliable way to reproduce it. 

It seems to happen when two instances of Repoman are opened and changes are made in one of those instances. The other instance does not update and becomes impossible to make changes in. The changed instance can be closed after being changed and the behavior is still the same.

This seems like a bit of a fringe case, but there is a noticeable delay between the time the gear icon is clicked and the Repoman window actually appears, and clicking it multiple times runs multiple instances, so it may not be that uncommon to run into. The same delay was present before this patch, but it was somewhat masked by the password prompt that appears immediately when clicking the gear icon. I'm not certain, but patching Pop Shop to prevent multiple instances might be a better way to approach it.

This was on Pop 18.04 and I haven't confirmed it on 19.10, but I can if that is helpful.

Other than that, this looks good. If we don't consider the above bug to be blocking, I'll approve this PR.

**Comment by brs17** [comment]
> There seems to be a condition which makes changes in Repoman not summon the password prompt which makes the settings unchangeable. @brs17 and I both ran into it, but I've finally found a reliable way to reproduce it.
> 
> It seems to happen when two instances of Repoman are opened and changes are made in one of those instances. The other instance does not update and becomes impossible to make changes in. The changed instance can be closed after being changed and the behavior is still the same.
> 
> This seems like a bit of a fringe case, but there is a noticeable delay between the time the gear icon is clicked and the Repoman window actually appears, and clicking it multiple times runs multiple instances, so it may not be that uncommon to run into. The same delay was present before this patch, but it was somewhat masked by the password prompt that appears immediately when clicking the gear icon. I'm not certain, but patching Pop Shop to prevent multiple instances might be a better way to approach it.
> 
> This was on Pop 18.04 and I haven't confirmed it on 19.10, but I can if that is helpful.
> 
> Other than that, this looks good. If we don't consider the above bug to be blocking, I'll approve this PR.

I would argue that since we both ran into this issue that it is blocking.

**Comment by isantop** [comment]
@pop-os/quality-assurance I think the issue is that the service has authorized the user, but the same (unauthenticated) client is requesting changes. 

 I added a modification to the launching script that will terminate existing Repoman processes before spawning a new one. This will help ensure we only have one client open at a time, and help minimize the impact of this bug. Under this setup, the only way someone could end up with two open at a time is by running one from the terminal after having opened it from Pop_Shop (and without opening it from Pop_Shop again).

**Review by leviport — APPROVED** [review]
That seems like a good workaround to me. It's a little strange to see Repoman close and reopen when clicking the gear multiple times, but that's a weird thing to do be doing anyway.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
