### PR TITLE
feat: System mirror entry

### LINKED ISSUE #23: Feature request: Add an option to change the repos to the ones hosted in your country.
I really like the OS but downloading packages from the US servers is slow. It could use an option to check for repos that have the lowest ping to the user and set them. It would really improve the user experience for users from other countries.

### PR DESCRIPTION
**Pull request by isantop**
Allows users to change to a different mirror, or to use multiple mirrors.

DeepinScreenshot_icon-library_20201013145847

Fixes #23

### CODE REVIEW

**Comment by jacobgkau** [comment]
Would it be feasible to have some sort of input checking when adding a new mirror? Since there's no drop-down or other method of choosing from a built-in list of mirrors, I looked up a [list of mirrors](https://launchpad.net/ubuntu/+archivemirrors) to test with. That list includes http, https, ftp, and rsync URLs; only http and https work out-of-the-box. Trying to `apt update` with an rsync source gives me the following message:

```
E: The method driver /usr/lib/apt/methods/rsync could not be found.
N: Is the package apt-transport-rsync installed?
```

(And I do not see an `apt-transport-rsync` package available.) FTP gives the following message:

```
E: The method 'ftp' is unsupported and disabled by default. Consider switching to http(s). Set Dir::Bin::Methods::ftp to "ftp" to enable it again.
```

I'm also able to enter malformed entries (such as omitting the protocol entirely), which results in:

```
E: Malformed entry 1 in sources file /etc/apt/sources.list.d/system.sources (URI parse)
E: The list of sources could not be read.
```

Perhaps we could at least check that the string starts with `http://` or `https://` before allowing it to be added, like the "Add Source" dialog on the Extra Sources page already does?

**Comment by isantop** [comment]
Doing it dynamically based on the currently-supported transports would be pretty difficult, as it would require generating (and maintaining) a list of the transports installed. It would be possible to check if it begins with http(s)://, but then we are artificially limiting users to those transports in the future. If that's something we're okay with, I can add that. Otherwise I think limiting it to the current selection is better.

**Comment by jacobgkau** [comment]
> Doing it dynamically based on the currently-supported transports would be pretty difficult, as it would require generating (and maintaining) a list of the transports installed.

Indeed. I see there's a `/usr/lib/apt/methods/` directory, but it contains ftp, which doesn't work, so I wouldn't consider that reliable.

> It would be possible to check if it begins with http(s)://, but then we are artificially limiting users to those transports in the future.

If other transports do not work in Pop!_OS right now, then I'm not sure we should worry about allowing users to attempt to add them right now. If other transports start being used and work in Pop later, then we can always update Repoman to allow them at that time, can't we?

I'd be more concerned about users being able to add a bad mirror (preventing them from using `apt` at all) and then, with another click, delete the default mirror (making it more difficult to recover.) Limiting to http(s):// wouldn't guarantee the mirror being added is valid, but it would at least prevent strings that would be highly unlikely to work. (I did remember `mirror://` and a mirrorlist seems to work fine, so we'd want to allow that as well if we went that route.)

Alternatively, would it be feasible to check whether the mirror is valid before saving it? I'd imagine this would be slower, but it would be more thorough than just checking the transport while also allowing any transport, so it could be a better solution.

**Comment by isantop** [comment]
> Alternatively, would it be feasible to check whether the mirror is valid before saving it? I'd imagine this would be slower, but it would be more thorough than just checking the transport while also allowing any transport, so it could be a better solution.

The problem with doing it that way is that it would prevent changes to sources unless the user is online and has a valid internet connection. It also requires that the mirror be online, which also can't be guaranteed. However, I think adding URL input validation to Repolib would help with this issue, as it allows us to catch invalid input and reject URIs which can't be valid at all.I'd prefer to add this in Repolib, as that assures it will be caught regardless of whether the user enters the URI in the command line or in repoman, and allows any future programs using repolib to benefit from that as well. 

> If other transports do not work in Pop!_OS right now, then I'm not sure we should worry about allowing users to attempt to add them right now. If other transports start being used and work in Pop later, then we can always update Repoman to allow them at that time, can't we?

There are also transport packages for S3, Tor, and https available, (none of which are installed by default in Pop which means that https mirrors don't work out of the box). Since enabling these is simply a matter of grabbing the packages for that particular transport, it's not necessarily correct to say they "aren't supported in Pop". I don't think we should be arbitrarily restricting what transports users can enter on the basis of it may not presently be supported, since if it isn't they'll get a message stating what the issue is and can fix the issue by enabling the transport or removing the mirror. Similar to validating if a source is online, we don't necessarily want to restrict users from entering arbitrary, technically valid but offline/incorrect sources.

**Comment by jacobgkau** [comment]
> There are also transport packages for S3, Tor, and https available, (none of which are installed by default in Pop which means that https mirrors don't work out of the box).

The [apt-transport-https package](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=apt-transport-https) is transitional since 18.04, it's not required for https to work and it does work out-of-the-box in Pop.

> Similar to validating if a source is online, we don't necessarily want to restrict users from entering arbitrary, technically valid but offline/incorrect sources.

I see your point. If our audience for Repoman is users who know the correct syntax, may be performing complex operations, and are able to read error messages (and would likely be able to edit the config files themselves but are choosing not to), that's fine. I was thinking more along the lines of users who may end up needing support when they get something wrong.

**Comment by isantop** [comment]
I definitely see that point as well, and I do think the "target user" trends more towards general users than advanced users. However, I want to avoid a situation where a more advanced concept is added separately and can't be edited in Repoman at all. Worse; if an advanced situation is configured manually and then accidentally removed in Repoman, it should be possible to re-add the removed mirror without needing to open a separate program.

In cases where Repoman hides advanced functionality from the user (like removing the `main` component from the Settings page), if the user makes changes to those settings, Repoman silently ignores it because there isn't UI for making those changes. So if a user disables `main` in the config file or from the command line, Repoman won't complain or automatically re-add it because it essentially just ignores the existence of `main` and doesn't care whether it's enabled or not. With the mirrors, it's a bit different because you want to list all of the options currently configured (Good design is honest), but you want to ensure that any changes one can make can be un-made.

**Comment by ids1024** [comment]
> Similar to validating if a source is online, we don't necessarily want to restrict users from entering arbitrary, technically valid but offline/incorrect sources.

Not sure if it would be awkward to implement, but it seems it could be helpful to have something like a warning icon next to sources and mirrors that appear to be invalid/offline. Plus tooltip text explaining the issue.

Then users could be informed though the UI, without any restriction in what they can do.

> I'd be more concerned about users being able to add a bad mirror (preventing them from using apt at all) and then, with another click, delete the default mirror (making it more difficult to recover.)

I suppose a "restore default mirrors" button would be fairly simple to provide?

**Comment by isantop** [comment]
There isn't currently a facility for designating a "default" mirror, however that could probably be added pretty simply. The nice thing about DEB822 sources is that they're extensible because compliant apt implementations are supposed to ignore unknown fields without modifications, (which is how Names are handled), so I'd just need to add an `X-Repolib-Default-Mirror` field for the system sources.

**Comment by isantop** [comment]
This PR now requires pop-os/repolib#22 and pop-os/repolib#23 

This will add native input validation and resetting the mirrors to defaults.

**Comment by jacobgkau** [comment]
This is looking like a great solution. The reset button is working as expected.

reset-button

@isantop How difficult would it be to either hide or disable the reset button until the mirrors have actually been changed (only show/enable when `URIs` is different from `X-Repolib-Default-Mirror`)? I see right now that if I remove the default line from the config file, the button doesn't go away until I close/re-open repoman, but if I change the URI list in the config file, Repoman updates its mirror list right away to reflect the change; it would obviously need to behave like the latter. Disabling might be better than hiding (so people know they'll have the option of resetting before they start changing things), but would make it clear that the button won't do anything if the URI list is already at its default (right now I can just keep clicking it, and it will also ask me for authentication even if it's not going to do anything.)

**Comment by isantop** [comment]
I could probably add that to the file-handler changed handler. It would be a bit more work. Would that be something that could be added post-release so as to focus on the `pop-upgrade` changes and the rest of everything going in?

**Review by jacobgkau — APPROVED** [review]
> Would that be something that could be added post-release so as to focus on the `pop-upgrade` changes and the rest of everything going in?

Fine with me, I don't think this will cause any major confusion, just a possible UI improvement. I've opened an issue to track it for later: https://github.com/pop-os/repoman/issues/76

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
