### PR TITLE
Port Repoman to Repolib

### PR DESCRIPTION
**Pull request by isantop**
Ports Repoman away from `software-properties-common` to use pop-os/repolib instead. This results in dramatically improved startup times, and removes a couple of issues that had been making working with SoftwareProperties fairly burdensome. 

This also helps pave the way for long-standing feature requests to be fulfilled, such as support for adding additional mirrors or changing to use a different mirror altogether.

Requires pop-os/iso#267

### CODE REVIEW

**Comment by jacobgkau** [comment]
I see that `http://apt.pop-os.org/proprietary` is part of `sources.list` after an upgrade from Focal to Groovy, and shows up as part of the "Legacy System Sources" item instead of as its own entry. https://github.com/pop-os/default-settings/pull/101 will convert system sources to deb822, while https://github.com/pop-os/default-settings/pull/97 will add `http://apt.pop-os.org/proprietary` in deb822 format if it's not present. Is there a reason `http://apt.pop-os.org/proprietary` isn't being converted to deb822 somewhere, at least if the line is enabled/unmodified?

I assume there's not a way to parse/work with legacy-format sources in the sources.list file alongside deb822 sources? Having the GUI tool open up a config file in a text editor would defeat the purpose for some users, they're still going to need to learn how to use the config file (they just won't have to know how to find/launch it.)

**Review by jacobgkau — DISMISSED** [review]
I am able to create a freeze/crash of Repoman if I click "Edit" on `sources.list` to open up Gedit, then, while that Gedit window's still open, go back to Repoman and try to select one of the other sources.

**Comment by leviport** [comment]
I'm seeing the same crash. It's looking like system sources are working correctly (and much faster), and adding and removing flatpak remotes seems fine as well.

**Comment by isantop** [comment]
I see what's going on. I need to open Gedit in a separate thread, otherwise Repoman waits for the Gedit process to complete before continuing.

**Comment by isantop** [comment]
> I see that `http://apt.pop-os.org/proprietary` is part of `sources.list` after an upgrade from Focal to Groovy, and shows up as part of the "Legacy System Sources" item instead of as its own entry. [pop-os/default-settings#101](https://github.com/pop-os/default-settings/pull/101) will convert system sources to deb822, while [pop-os/default-settings#97](https://github.com/pop-os/default-settings/pull/97) will add `http://apt.pop-os.org/proprietary` in deb822 format if it's not present. Is there a reason `http://apt.pop-os.org/proprietary` isn't being converted to deb822 somewhere, at least if the line is enabled/unmodified?

The source could also be converted, however as it's not strictly a system source, it was not at the time. That can be changed too, though. 

> I assume there's not a way to parse/work with legacy-format sources in the sources.list file alongside deb822 sources? Having the GUI tool open up a config file in a text editor would defeat the purpose for some users, they're still going to need to learn how to use the config file (they just won't have to know how to find/launch it.)

Because the sources in sources.list are often going to use wildly different URIs, suites, and types, it's very difficult to parse them, allow modifications, and save them back to the sources.list file. Software Properties worked around this by building a large internal database of sources, however, it needed to build this every time the library was loaded, hence its slowness, and it also tended to be somewhat error prone, leading to bugs like #70. Parsing them and moving them into separate files in sources.list.d would be fairly easy, however since sources.list is often modified by scripts or other installation commands, that could mean users end up with duplicate sources. 

As an example, 1password's deb package adds a line for their repo into `sources.list` instead of a sources file in `sources.list.d`. Moving it to sources.list.d would mean users end up with another line in `sources.list` when they update the package. Perhaps one way to work around this would be for something to parse the `sources.list` file, and if it finds no valid sources there just delete the file (which will prevent the item from showing up in Repoman). That way users aren't generally confused about the legacy file/format.

The `sources.list` file does not support deb822 sources; these need to be placed in a file in `sources.list.d` ending in `.sources`, instead of `.list`. That's how APT internally determines what format sources the file contains.

**Comment by isantop** [comment]
@jacobgkau @leviport I updated the PR to move the Gedit process to its own thread, and also made the add process threaded (as I noticed it could also freeze the GUI if it takes too long (usually if the user is adding a PPA from launchpad).

Related to this, Repoman uses a file monitor to watch for changes in the sources.list.d files, as the threads update the files asynchronously and that's a better way to check. Additionally, we get the benefit of the list updating dynamically if a user makes changes to sources from outside Repoman

**Review by leviport — APPROVED** [review]

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
