### PR TITLE
Upstream master

### PR DESCRIPTION
**Pull request by isantop**
Merge in changes from upstream. 

Includes:

Fixes pop-os/gtk-theme#180

### CODE REVIEW

**Comment by mmstick** [comment]
Build error:

```
creating /<<PKGBUILDDIR>>/debian/repoman/usr/share
09:49:32 creating /<<PKGBUILDDIR>>/debian/repoman/usr/share/metainfo
09:49:32 copying data/repoman.appdata.xml -> /<<PKGBUILDDIR>>/debian/repoman/usr/share/metainfo
09:49:32 creating /<<PKGBUILDDIR>>/debian/repoman/usr/share/applications
09:49:32 error: can't copy 'data/repoman.desktop': doesn't exist or not a regular file
09:49:32 E: pybuild pybuild:336: install: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py install --root '/<<PKGBUILDDIR>>/debian/repoman' 
09:49:32 dh_auto_install: pybuild --install -i python{version} -p 3.6 --dest-dir /<<BUILDDIR>>/repoman-1.0.1\~1533763598\~18.04\~a8ad5f9/debian/repoman returned exit code 13
09:49:32 debian/rules:4: recipe for target 'binary' failed
09:49:32 make: *** [binary] Error 25
```

**Comment by isantop** [comment]
Should be fixed as of 9d3f819

**Review by brs17 — APPROVED** [review]
__Before__
screenshot from 2018-08-10 10-12-48


__After__
screenshot from 2018-08-10 10-15-41

Looks good to me!

**Comment by brs17** [comment]
I forgot to check what these changes did to repoman in the current theme. I think this is a regression: 

screenshot from 2018-08-10 21-19-21

**Pull request merged**
