### PR TITLE
Provide Italian translation

### PR DESCRIPTION
**Pull request by mirkobrombin**

### CODE REVIEW

**Review by isantop — APPROVED** [review]
Everything looks good technically. We just need to make sure the specified translations appear in the program with the locale set to Italian

**Comment by isantop** [comment]
I pushed a repo-local copy of the branch, so it should build in our CI shortly.

**Comment by mirkobrombin** [comment]
> Everything looks good technically. We just need to make sure the specified translations appear in the program with the locale set to Italian

They should.

**Review by jacobgkau — APPROVED** [review]
>> Everything looks good technically. We just need to make sure the specified translations appear in the program with the locale set to Italian
>
> They should.

They do! Thanks again.

**Pull request merged**
