### PR TITLE
Make package description more descriptive

### LINKED ISSUE #115: repoman package: Package information sorely lacking (though amusing)
**Distribution:**
 
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version:**

```
repoman:
  Installed: 2.4.0~1692737584~22.04~62b699a
  Candidate: 2.4.0~1692737584~22.04~62b699a
  Version table:
 *** 2.4.0~1692737584~22.04~62b699a 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

The package description, "**Hey man, let's go do crimes. Yeah, let's install software and not pay.**", while mildly amusing, is insufficient. Nothing helpful in `/usr/share/doc/repoman/` either.

**Steps to reproduce (if you know):**

```
$ apt-cache show repoman
Package: repoman
Architecture: all
Version: 2.4.0~1692737584~22.04~62b699a
Priority: extra
Section: x11
Maintainer: Ian Santopietro <ian@system76.com>
Installed-Size: 208
Depends: python3:any (>= 3.4~), gir1.2-gtk-3.0, python3-repolib (>= 2.0)
Recommends: gir1.2-flatpak-1.0
Filename: pool/jammy/repoman/62b699ab9cd3f12a598760eeac88ab625309b18b/repoman_2.4.0~1692737584~22.04~62b699a_all.deb
Size: 33584
MD5sum: 3362fc589dcda1e1fda3564179f3c59f
SHA1: 186b606cb2c702d5366a5d9ab4c01b522ebcf487
SHA256: 118ae1a8c13a2b753390324012f049d4b5539005dc25d1f85c45614279946a6e
SHA512: 48b54917b9a9f091d7fa86694cc772688259748d9e8267a61a1424979a92391ba64c47e4b7f9359547207d454cb87669e5f40eceb5fcef6a60e2d8d36cf0fea7
Description: Repoman
 Hey man, let's go do crimes. Yeah, let's install software and not pay.
Description-md5: af49476b2dfc6df2cfbe7dd6990c1eb3

$ apt-cache rdepends repoman
repoman
Reverse Depends:
  pop-shop
  pop-transition
```

**Expected behavior:**

I expected to be told why I would want to keep the package around without needing to resorting to `apt-cache rdepends`...

### PR DESCRIPTION
**Pull request by leviport**
- Puts the easter-egg phrase in quotes
- Copies the description from README.md into package description
- Adds a mention of Flatpak sources

Closes https://github.com/pop-os/repoman/issues/115

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by kjcole** [comment]
> * Puts the easter-egg phrase in quotes
> * Copies the description from README.md into package description
> * Adds a mention of Flatpak sources
> 
> Closes #115

The pull-request fixes things well, but I would also suggest changing the  one-line short description to something like "Repository configuration manager" so that issuing `dpkg -l repoman` would have a less redundant description field. (It currently has the description "Repoman".)

**Comment by leviport** [comment]
@kjcole How's that?

**Review by jacobgkau — APPROVED** [review]
Shows up properly in `dpkg` and `apt` output.

Before:
Screenshot from 2023-08-23 11-14-19

After:
Screenshot from 2023-08-23 11-14-52

I wouldn't be opposed to dropping the joke phrase altogether (repoman doesn't install things itself, anyway), but the new description is still more useful than the old one.

**Comment by jacobgkau** [comment]
I do wonder if there's a way to insert a newline in the description rather than needing the `.` line.

**Comment by leviport** [comment]
Yeah I wasn't sure about that. I just saw them at https://github.com/pop-os/system76-driver/blob/3e9def1cb3789fb1016c14777d8c6df02de15956/debian/control#L64 and mimicked that.

**Pull request merged**
