### PR TITLE
Show error dialogs when sources have errors

### PR DESCRIPTION
**Pull request by isantop**
Now that Repoman is no logner crashing when there are invalid sources, it would be very helpful to inform the user when their sources have errors. This PR adds an error dialog when repolib detects sources files with invalid entries, listing the filenames of the bad files and instructions for getting more information about the errors.

image

This doesn't prevent valid sources from loading and being modified in the GUI. 

Requires pop-os/repolib#26

### CODE REVIEW

**Comment by isantop** [comment]
For testing, add one or two invalid sources, such as:

```
# X-Repolib-Name: Invalid Source
deb http://example.com/ubuntu
# Missing a suite/component
```

With this in place, the error message should present when Repoman opens.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The dialog is working. When I perform certain operations, it appears three times in a row:

- Turning components on/off on the Settings page
- Adding a PPA

For other operations (such as removing a PPA), the dialog only appears once. I could go either way on whether it should appear when performing operations or only at launch, but it's kind of annoying when I have to click "Close" three times in a row (and I can see less patient users giving up and assuming it's stuck in a loop before they get to three clicks.) Is that something that can be improved?

**Comment by isantop** [comment]
I'll look at improving the situation. That shouldn't be too hard to complete

**Comment by isantop** [comment]
@jacobgkau I found the problem. The file watch monitor triggers the list to reload several times after various operations, and since the reload method was what originally spawned the error dialog, it too would be loaded several times. Normally, these reloads happen too fast for the user to take notice; however, since we were displaying the dialog, it was noticeable. 

b924a0e changes this to only spawn the error dialog when Repoman initially opens. It also spawns the dialog after the Repoman Window is created and displayed, which I believe is better UX anyway as it makes it more clear that the Dialog is part of Repoman (whereas previously the dialog was initially displayed before the window.

Repoman will still log a `WARNING` message to the console when it reloads the sources list; most users who open Repoman via Pop_Shop will not see these, however if a user manually runs the application via a terminal, they will be informed about the invalid sources.

**Comment by jacobgkau** [comment]
@isantop The behavior looks good now. One little aesthetic thing, whether I launch repoman from the terminal or the Pop!_Shop, the dialog ends up looking like it's unfocused (as the main Repoman window behind it is focused instead):

close-button

This doesn't create any usability problems, because I'm still able to press Esc, Space, or Enter to dismiss the dialog (aside from just clicking the Close button.) However, it would be more apparent that the keyboard can be used to dismiss the dialog if it was focused (and it's confusing that a dialog pops up without being focused.) It almost looks like the dialog is focused at first and then focus is moved back to Repoman, do you know what might be causing that and how easy it would be to change?

**Comment by isantop** [comment]
That didn't happen in my initial testing, but it is occasionally now, leading me to believe that something external is setting the focus and that thing is inconsistent. 0b9ace8734f9681658e6271fa45a78e6e32b7a22 moves the dialog init so that it always gets focus

**Comment by jacobgkau** [comment]
The dialog's still unfocused at launch on `c186ac2`: https://www.dropbox.com/s/y8h1c8t00qukzwk/repoman-pr84-screencast1.mp4?dl=0

**Comment by isantop** [comment]
I honestly have no idea. The dialog always opens focused for me here, regardless of whether I open it from Pop Shop or from the terminal

**Comment by isantop** [comment]
Actually, I think it might be something with Pop Shell. If I enable it, it always spawns unfocused, but if I disable it, it spawns focused.

**Comment by isantop** [comment]
@jacobgkau I believe this is now fixed as of d1f6e87b860b68618d25bd9c86c81c76daaca241

**Review by jacobgkau — APPROVED** [review]
Dialog focus looks good now, regression testing passed.

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
