### PR TITLE
Repolib 2

### PR DESCRIPTION
**Pull request by isantop**
Updates Repoman to use RepoLib 2. Ensures that the package will not be upgraded without the requisite repolib version via `debian/control`.

This should probably be merged prior to merging the Repolib `repolib2` PR as merging that one first would cause Repoman breakage in existing installs. Both PRs use the same branch name, so they can be tested simultaneously.

### CODE REVIEW

**Review by n3m0-22 — COMMENTED** [review]
This may be outside the purview of this PR, but https://github.com/pop-os/repoman/issues/100 is still an issue.

**Comment by isantop** [comment]
> This may be outside the purview of this PR, but #100 is still an issue.

That would be; the `X-Repolib-Default-Mirror` key is used for that button and it's encoded directly in `/etc/apt/sources.list.d/system.sources`. Updating `default-settings` or otherwise updating that file will correct that issue.

**Review by n3m0-22 — COMMENTED** [review]
I am running into problems while going through the TESTING.md check list. This may just be a case of the testing file needing to be updated. For instance, I'm not seeing results matching when comparing changes (enabling source) in `repoman` vs `software-properties-gtk`. Also after adding `ppa:system76/proposed` I can set the version to `xenial` but if I set type to `Source Code` I get the following.

repoman

**Review by n3m0-22 — DISMISSED** [review]

**Review by mmstick — DISMISSED** [review]

**Comment by isantop** [comment]
@n3m0-22 That was definitely a bug. I've updated Repolib and I believe the bug is now fixed as of pop-os/repolib@b1845bd

**Review by n3m0-22 — DISMISSED** [review]
The update has resolved the issue. I went through all the testing for Repoman and Repolib again. with no issues this time. I will start updating the testing files to match these updates.

**Review by n3m0-22 — APPROVED** [review]

**Review by mmstick — APPROVED** [review]

**Pull request merged**
